services:

  dwh-raw-layer-database:
    extends:
      file: dwh/layers/raw/docker-compose.raw.yaml
      service: dwh-raw-layer-database

  dwh-ods-layer-database:
    extends:
      file: dwh/layers/ods/docker-compose.ods.yaml
      service: dwh-ods-layer-database

  dwh-dds-layer-database:
    extends:
      file: dwh/layers/dds/docker-compose.dds.yaml
      service: dwh-dds-layer-database

  dwh-mart-layer-database:
    extends:
      file: dwh/layers/mart/docker-compose.mart.yaml
      service: dwh-mart-layer-database

  dwh-raw-layer-migrations:
    extends:
      file: dwh/layers/raw/docker-compose.raw.yaml
      service: dwh-raw-layer-migrations

  dwh-ods-layer-migrations:
    extends:
      file: dwh/layers/ods/docker-compose.ods.yaml
      service: dwh-ods-layer-migrations

  dwh-dds-layer-migrations:
    extends:
      file: dwh/layers/dds/docker-compose.dds.yaml
      service: dwh-dds-layer-migrations

  dwh-mart-layer-migrations:
    extends:
      file: dwh/layers/mart/docker-compose.mart.yaml
      service: dwh-mart-layer-migrations
