services:

  ods-database:
    extends:
      file: dwh/layers/ods/docker-compose.ods.yaml
      service: ods-database

  dds-database:
    extends:
      file: dwh/layers/dds/docker-compose.dds.yaml
      service: dds-database

  mart-database:
    extends:
      file: dwh/layers/mart/docker-compose.mart.yaml
      service: mart-database

  ods-migrations:
    extends:
      file: dwh/layers/ods/docker-compose.ods.yaml
      service: ods-migrations

  dds-migrations:
    extends:
      file: dwh/layers/dds/docker-compose.dds.yaml
      service: dds-migrations

  mart-migrations:
    extends:
      file: dwh/layers/mart/docker-compose.mart.yaml
      service: mart-migrations
