apiVersion: v1
kind: Service
metadata:
  name: zookeeper-sorting-hat-system-design-org
  labels:
    app: zookeeper
spec:
  ports:
  - port: 2181
    targetPort: 2181
    name: client
  selector:
    app: zookeeper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:7.6.1
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          valueFrom:
            configMapKeyRef:
              name: config
              key: KAAS_ZOOKEEPER_PORT
        ports:
        - containerPort: 2181
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - echo ruok | nc -w 2 localhost 2181
          initialDelaySeconds: 5
          periodSeconds: 5