apiVersion: v1
kind: Service
metadata:
  name: dbaas-sorting-hat-system-design-org
  labels:
    app: database
    app.kubernetes.io/name: database
spec:
  ports:
  - name: database
    port: 5432
    targetPort: 5432
  selector:
    app: database

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
spec:
  serviceName: database
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: postgres
        image: postgres:alpine3.19
        ports:
          - containerPort: 5432
        env:
          - name: PGDATA
            value: /var/lib/postgresql/data/hse-system-design
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: config
                key: DATABASE_NAME
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: config
                key: DATABASE_USERNAME
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: config
                key: DATABASE_PASSWORD
          - name: DATABASE_HOST
            valueFrom:
              configMapKeyRef:
                name: config
                key: DATABASE_HOST
          - name: DATABASE_PORT
            valueFrom:
              configMapKeyRef:
                name: config
                key: DATABASE_PORT
        
        volumeMounts:
          - name: postgres-data
            mountPath: /var/lib/postgresql/data

  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi

  