global:
  scrape_interval: 1s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: "prober"
    static_configs:
      - targets: ["prober.system-design.org:6200"]
