apiVersion: v1
kind: Service
metadata:
  name: http-api-sorting-hat-system-design-org
spec:
  type: LoadBalancer
  selector:
    app: http-api
  ports:
    - protocol: TCP
      port: 6100
      targetPort: 6100
  sessionAffinity: None

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-api
  labels:
    app: http-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: http-api
  template:
    metadata:
      labels:
        app: http-api
    spec:
      containers:
      - name: http-api
        image: hse-system-design-http-api:latest
        args: ["--start-http-api"]
        imagePullPolicy: Never
        ports:
        - containerPort: 6100
        livenessProbe:
          httpGet:
            path: /api/v1/healthcheck
            port: 6100
          failureThreshold: 1
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v1/healthcheck
            port: 6100
          failureThreshold: 1
          initialDelaySeconds: 15
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /api/v1/healthcheck
            port: 6100
          failureThreshold: 10
          initialDelaySeconds: 30
          periodSeconds: 10
        env:
          - name: DATABASE_HOST
            valueFrom:
              configMapKeyRef:
                name: config
                key: DATABASE_HOST
          - name: DATABASE_PORT
            valueFrom:
              configMapKeyRef:
                name: config
                key: DATABASE_PORT
          - name: DATABASE_NAME
            valueFrom:
              configMapKeyRef:
                name: config
                key: DATABASE_NAME
          - name: DATABASE_USERNAME
            valueFrom:
              configMapKeyRef:
                name: config
                key: DATABASE_USERNAME
          - name: DATABASE_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: config
                key: DATABASE_PASSWORD
          - name: HTTP_API_PORT
            valueFrom:
              configMapKeyRef:
                name: config
                key: HTTP_API_PORT
          - name: KAAS_BROKER_PORT
            valueFrom:
              configMapKeyRef:
                name: config
                key: KAAS_BROKER_PORT
          - name: KAAS_BROKER_HOST
            valueFrom:
              configMapKeyRef:
                name: config
                key: KAAS_BROKER_HOST
          - name: KAFKA_BOOTSTRAP_SERVERS
            value: $(KAAS_BROKER_HOST):$(KAAS_BROKER_PORT)
          - name: KAFKA_GROUP_ID
            valueFrom:
              configMapKeyRef:
                name: config
                key: KAFKA_GROUP_ID
          - name: TOPIC_NAME_RESULTS
            valueFrom:
              configMapKeyRef:
                name: config
                key: KAFKA_RESULT_TOPIC_NAME
          - name: TOPIC_NAME_TRIGGERS
            valueFrom:
              configMapKeyRef:
                name: config
                key: KAFKA_TRIGGER_TOPIC_NAME
          - name: HTTP_API_HOST
            value: "0.0.0.0"
